import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import mergeClasses from "@/utils/mergeClasses";
import Providers from "@/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Twitter",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mergeClasses(inter.className, "debug-screens")}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
