import type { Metadata } from "next";
import SideBar from "@/components/sidebar";
import { AuthRoute } from "@/providers/AuthProvider";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Twitter | Home",
  description: "Generated by create next app",
};

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthRoute>
      <div className="grid grid-cols-12 h-screen w-[65%] mx-auto">
        <SideBar />
        <div className="col-span-6 flex flex-col border-x border-zinc-700 mr-6">
          <Header />
          {children}
        </div>
        <div className="col-span-3 border-x border-zinc-700"></div>
      </div>
    </AuthRoute>
  );
}
