"use client";
import type { Metadata } from "next";
import SideBar from "@/components/side-bar";
import { AuthRoute } from "@/providers/AuthProvider";
import ExploreBar from "../../components/explore-bar";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Twitter | Home",
//   description: "Generated by create next app",
// };

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();

  if (path.includes("messages"))
    return (
      <AuthRoute>
        <div className=" overflow-y-scroll">
          <div className="grid grid-cols-18 h-screen w-[65%] mx-auto">
            <SideBar className="col-span-1" />
            {children}
          </div>
        </div>
      </AuthRoute>
    );

  return (
    <AuthRoute>
      <div className="overflow-y-scroll">
        <div className="grid grid-cols-20 h-screen w-[65%] mx-auto gap-4">
          <SideBar className="col-span-5" />
          <div className="col-span-10 flex flex-col border-x border-zinc-800">
            {children}
          </div>
          <ExploreBar />
        </div>
      </div>
    </AuthRoute>
  );
}
