import type { Metadata } from "next";
import SideBar from "@/components/side-bar";
import { AuthRoute } from "@/providers/AuthProvider";
import Header from "@/components/header";
import ExploreBar from "@/components/explore-bar";

export const metadata: Metadata = {
  title: "Twitter | Home",
  description: "Generated by create next app",
};

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthRoute>
      <div className="overflow-y-scroll">
        <div className="grid grid-cols-12 h-screen w-[65%] mx-auto">
          <SideBar />
          <div className="col-span-6 flex flex-col border-x border-zinc-700 mr-6">
            <Header />
            {children}
          </div>
          <ExploreBar />
        </div>
      </div>
    </AuthRoute>
  );
}
