import { GoogleProvider } from "@/providers/GoogleProvider";
import { Twitter } from "lucide-react";
import { Metadata } from "next";
import Link from "next/link";
import React from "react";
import { BsTwitter } from "react-icons/bs";

export const metadata: Metadata = {
  title: "Twitter | Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GoogleProvider>
      <div className="h-screen w-screen flex flex-col">
        <div className="flex justify-between items-center px-40 absolute w-full top-0 border border-x-0 border-t-0 border-b border-zinc-800">
          <div className="text-5xl w-fit p-4 rounded-full cursor-pointer active:scale-[0.95] transition-all">
            <Link href="/">
              <BsTwitter />
            </Link>
          </div>
          <div className="flex gap-4 font-semibold">
            <button className="bg-black border border-zinc-700 px-4 py-2 rounded-lg text-md active:scale-[0.95] transition-all hover:bg-zinc-800">
              <Link href="/sign-in">Sign In</Link>
            </button>
            <button className="bg-white text-black px-4 py-2 rounded-lg text-md active:scale-[0.95] transition-all hover:bg-zinc-300">
              <Link href="/sign-up">Sign Up</Link>
            </button>
          </div>
        </div>
        <div className="flex-1 flex flex-col justify-center items-center gap-4 ">
          {children}
        </div>
      </div>
    </GoogleProvider>
  );
}
